name: secret-env-invocation

on: [workflow_dispatch]


jobs:
  ci:
    name: CI-Invocation
    uses: ./.github/workflows/reusable-secret-env.yaml
    # 'secrets: inherit' along with the 'env: ${{ secrets }}' in downstream actions will make all secrets available as env variables in downstream actions
    secrets: inherit
    with:
      env_vars: |
        ENV_VARIABLE_FOO=HELLO
        ENV_VARIABLE_BAR=WORLD
