name: invocable-secret-env-composite

on: [workflow_dispatch]


jobs:
  ci:
    name: reusable-secret-env-composite invocation
    uses: ./.github/workflows/reusable-secret-env-composite.yaml
    # 'secrets: inherit' along with the 'env: ${{ secrets }}' in downstream actions will make all secrets available as env variables in downstream actions
    secrets: inherit
    with:
      env_vars: |
        ENV_VARIABLE_FOO=HELLO
        ENV_VARIABLE_BAR=WORLD
