name: reusable-secret-env-composite

on:
  workflow_call:
    inputs:
      env_vars:
        description: A literal block scalar of environment variables to set up, given in env=value format.
        required: false
        type: string

jobs:
  build:
    name: secret-env-variables
    runs-on: ubuntu-latest
    steps:
      - name: echo env secrets
        uses: tsanton/github-action-environment-management/actions/echo-env-secrets@main
        env: ${{ secrets }}
        with:
          env_vars: ${{ inputs.env_vars }}
