name: secret-env

on:
  workflow_call:
    inputs:
      env_vars:
        description: A literal block scalar of environment variables to set up, given in env=value format.
        required: false
        type: string


jobs:
  build:
    name: secret-env-variables
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        if: ${{ inputs.env_vars }}
        run: |
          for i in "${{ inputs.env_vars }}"
          do
            printf "%s\n" $i >> $GITHUB_ENV
          done

      - name: echo environment variables
        env: ${{ secrets }}
        run: |
          printenv
